### ISSUE TITLE
How to emulate hover? CSS :hover doesn't work

### ISSUE THREAD

**Issue by patrickbolle** [klummy/VueLinkPopover#2]
Hi there. 
Love the component so far. Trying to style the popover__content, but I can't bring it up in Chrome and work with the styling. I've tried adding the Chrome hover, active, focus states to the popover link, but nothing works.

Any way I can emulate this so I can work with the styling?

**Comment by patrickbolle** [comment]
Actually, I've been able to 'freeze' the frame using dev tools (timeout, then open debugger) - but no matter what I do, I can't change the styling of the popover__content...
In devtools css it displays as ' .popover__content[data-v-7b5a9d03] '.

**Comment by klummy** [comment]
@patrickbolle Sorry for the late response. I will look into it this evening. I suspect it likely has to do with the scoped nature of the styles.

**Comment by klummy** [comment]
@patrickbolle v2.0 has been released which allows you to customise easily using custom themes and transitions as well as improved documentation. You can style the hover state for the popover__content using `.popover__content:hover { background-color: red }`.
