### ISSUE TITLE
Error following the instructions

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [klummy/VueLinkPopover#4]
Following the approach of: 

 import { LinkPopover } from 'vue-link-popover'

  // Register component
  components: {
  LinkPopover
  }
I get the following error:

  [Vue warn]: Unknown custom element: <link-popover> - did you register the component correctly? For recursive components, make sure to provide the "name" option.   (found in <compName> at <path>)
My webpack config is pretty much what comes out the box - I made little change.
Is this an issue with my approach?

It works fine if I register it globally.

**Comment by klummy** [comment]
Hey @MatthewJamesBoyle,

Could you try `import LinkPopover from 'vue-link-popover'`?

I might have made an error in the documentation. Do let me know if that fixed it

**Comment by MatthewJamesBoyle** [comment]
You are correct- was a little typo in the documentation I should have been smart enough to spot. However, this doesn't fully resolve the issue unfortunately. I now have:
[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <LinkPopover>). any suggestions on this one?
